@file:Suppress("KDocUnresolvedReference")

package com.onenowy.moshipolymorphicadapter

/**
 * Use [PolymorphicAdapterType] to specify adapter generated by reflection or annotation processor with [generator] value in [@JsonClass].
 * ```
 * @JsonClass(generateAdapter = true, generator = PolymorphicAdapterType.NAME_ADAPTER)
 * ```
 * For [ValuePolymorphicAdapter], [:{labelKey}], the name of field or property that determine type, is required with [PolymorphicAdapterType].
 * ```
 * @JsonClass(generateAdapter = true, generator = PolymorphicAdapterType.VALUE_ADAPTER_INT + ":labelKey")
 * ```
 */
object PolymorphicAdapterType {
    const val NAME_POLYMORPHIC_ADAPTER = "MoshiPolymorphic.Name"
    const val VALUE_POLYMORPHIC_ADAPTER_INT = "MoshiPolymorphic.Int"
    const val VALUE_POLYMORPHIC_ADAPTER_LONG = "MoshiPolymorphic.Long"
    const val VALUE_POLYMORPHIC_ADAPTER_DOUBLE = "MoshiPolymorphic.Double"
    const val VALUE_POLYMORPHIC_ADAPTER_STRING = "MoshiPolymorphic.String"
    const val VALUE_POLYMORPHIC_ADAPTER_BOOLEAN = "MoshiPolymorphic.Boolean"
}