package com.onenowy.moshipolymorphicadapter.moshipolymorphicadapterfactory.annotations

@Retention(AnnotationRetention.RUNTIME)
@Target(AnnotationTarget.CLASS)
annotation class NameAdapterFactoryReflection
